### ISSUE TITLE
check xrp library to support sending transactions

### ISSUE THREAD

**Issue by Imdavyking** [Dhali-org/xrpl.dart#5]
https://pub.dev/packages/xrp

**Comment by desimmons** [comment]
Thanks! Is this an issue that is being highlighted with `xrpl.dart`? If not, I'll close it.

**Comment by Imdavyking** [comment]
you can build on it and also enable sendXRP...this would ensure it works on all platforms

**Comment by Imdavyking** [comment]
you can build on it and also enable sendXRP...this would ensure it works on all platforms

**Comment by robbie-daniels** [comment]
Thanks!  We're actually looking at changing our implementation of this library anyway, since it only works for web at the moment.  We'll let you know once that's finished!
